In [243]:
import numpy as np

In [244]:
list1 = [4,6,2]
list1.append(5)
print(list1)

[4, 6, 2, 5]


In [245]:
#transform an list into a numpy array
numpy_array = np.array(list1)

In [246]:
print(numpy_array)

[4 6 2 5]


In [247]:
#generates an array from a csv or a txt
tree = np.genfromtxt("iris-data-clean.csv",delimiter=",")

In [248]:
#save an array into a text or a csv 
np.savetxt('testnp.txt',list1,delimiter=" ")

In [249]:
#by default load as float
list2 = np.genfromtxt('testnp.txt',delimiter=" ",dtype=int)
print(list2)

[4 6 2 5]


In [250]:
#generates a random nb array
np.random.rand(3,4)*2-1

array([[ 0.57695021,  0.81194649, -0.72327667,  0.35064305],
       [ 0.84336844, -0.11256186,  0.91252638, -0.19408622],
       [-0.08071288,  0.88762643, -0.91121176, -0.84189914]])

In [251]:
#generates an array of random int
np.random.randint(10,size=(3,2))

array([[0, 9],
       [8, 3],
       [5, 6]])

In [252]:
np.zeros((3,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [253]:
print(tree.size)
print(tree.shape)

750
(150, 5)


In [254]:
#convertir le type d'un array
print(tree.dtype)
tree.astype(int)

float64


array([[-2147483648, -2147483648, -2147483648, -2147483648, -2147483648],
       [          5,           3,           1,           0, -2147483648],
       [          4,           3,           1,           0, -2147483648],
       [          4,           3,           1,           0, -2147483648],
       [          4,           3,           1,           0, -2147483648],
       [          5,           3,           1,           0, -2147483648],
       [          5,           3,           1,           0, -2147483648],
       [          4,           3,           1,           0, -2147483648],
       [          5,           3,           1,           0, -2147483648],
       [          4,           2,           1,           0, -2147483648],
       [          4,           3,           1,           0, -2147483648],
       [          5,           3,           1,           0, -2147483648],
       [          4,           3,           1,           0, -2147483648],
       [          4,           3,     

In [255]:
# convertir un array en list python
list3 = tree.tolist()
list3

[[nan, nan, nan, nan, nan],
 [5.1, 3.5, 1.4, 0.2, nan],
 [4.9, 3.0, 1.4, 0.2, nan],
 [4.7, 3.2, 1.3, 0.2, nan],
 [4.6, 3.1, 1.5, 0.2, nan],
 [5.0, 3.6, 1.4, 0.2, nan],
 [5.4, 3.9, 1.7, 0.4, nan],
 [4.6, 3.4, 1.4, 0.3, nan],
 [5.0, 3.4, 1.5, 0.24999999999999997, nan],
 [4.4, 2.9, 1.4, 0.24999999999999997, nan],
 [4.9, 3.1, 1.5, 0.24999999999999997, nan],
 [5.4, 3.7, 1.5, 0.24999999999999997, nan],
 [4.8, 3.4, 1.6, 0.24999999999999997, nan],
 [4.8, 3.0, 1.4, 0.1, nan],
 [5.7, 3.0, 1.1, 0.1, nan],
 [5.8, 4.0, 1.2, 0.2, nan],
 [5.7, 4.4, 1.5, 0.4, nan],
 [5.4, 3.9, 1.3, 0.4, nan],
 [5.1, 3.5, 1.4, 0.3, nan],
 [5.7, 3.8, 1.7, 0.3, nan],
 [5.1, 3.8, 1.5, 0.3, nan],
 [5.4, 3.4, 1.7, 0.2, nan],
 [5.1, 3.7, 1.5, 0.4, nan],
 [4.6, 3.6, 1.0, 0.2, nan],
 [5.1, 3.3, 1.7, 0.5, nan],
 [4.8, 3.4, 1.9, 0.2, nan],
 [5.0, 3.0, 1.6, 0.2, nan],
 [5.0, 3.4, 1.6, 0.4, nan],
 [5.2, 3.5, 1.5, 0.2, nan],
 [5.2, 3.4, 1.4, 0.2, nan],
 [4.7, 3.2, 1.6, 0.2, nan],
 [4.8, 3.1, 1.6, 0.2, nan],
 [5.4, 3.4, 1.5, 0.4, na

In [256]:
print(tree[2])
print(tree[2,3])

[4.9 3.  1.4 0.2 nan]
0.2


In [257]:
#de la troisième (0 1 2 3) à la 9ieme ligne
tree[3:10]

array([[4.7 , 3.2 , 1.3 , 0.2 ,  nan],
       [4.6 , 3.1 , 1.5 , 0.2 ,  nan],
       [5.  , 3.6 , 1.4 , 0.2 ,  nan],
       [5.4 , 3.9 , 1.7 , 0.4 ,  nan],
       [4.6 , 3.4 , 1.4 , 0.3 ,  nan],
       [5.  , 3.4 , 1.5 , 0.25,  nan],
       [4.4 , 2.9 , 1.4 , 0.25,  nan]])

In [258]:
#convert tree array in integers
tree = tree.astype(int)

In [259]:
#change each columns to random int
tree[:,0]= np.random.randint(4,size=(len(tree)))
tree[:,1]= np.random.randint(10,size=(len(tree)))
tree[:,2]= np.random.randint(5,size=(len(tree)))
tree[:,3]= np.random.randint(3,size=(len(tree)))
tree[:,4]= np.random.randint(7,size=(len(tree)))

In [260]:
test = tree
#to sort each row
test.sort(axis=1)
#to sort each column
test.sort(axis=0)
#convert a n-D array into a vector
test = test.flatten()
test.shape

(750,)

In [261]:
#transpose
tree = tree.T
tree = tree.T

In [262]:
# reshape an array into a 150x5 matrix
test = test.reshape(150,5)

In [263]:
# resize is like reshape but adds zeros if dimensions are higher than expected
array = np.array([[2,4,6,5],[3,2,4,5],[4,8,9,7]])
array.resize(6,4)
array

array([[2, 4, 6, 5],
       [3, 2, 4, 5],
       [4, 8, 9, 7],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [264]:
#concatenate rows
array2 = np.ones((2,4),dtype=int)
np.concatenate((array,array2), axis=0)

#concatenate columns
array2 = np.ones((6,2),dtype=int)
np.concatenate((array,array2), axis=1)

array([[2, 4, 6, 5, 1, 1],
       [3, 2, 4, 5, 1, 1],
       [4, 8, 9, 7, 1, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 1, 1]])

In [265]:
#split the array into sub-arrays by row
print(array)
array_split,array_split2 = np.split(array,2)
print("\n{}\n\n{}".format(array_split,array_split2))

[[2 4 6 5]
 [3 2 4 5]
 [4 8 9 7]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[2 4 6 5]
 [3 2 4 5]
 [4 8 9 7]]

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [266]:
#split the array by columns
print(array)
split1, split2 = np.hsplit(array,2)
print("\n{}\n\n{}".format(split1,split2))

[[2 4 6 5]
 [3 2 4 5]
 [4 8 9 7]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

[[2 4]
 [3 2]
 [4 8]
 [0 0]
 [0 0]
 [0 0]]

[[6 5]
 [4 5]
 [9 7]
 [0 0]
 [0 0]
 [0 0]]


In [267]:
#add one or more numbers into an array, becomes a vector
np.append(array,(2,3,4))
#insert before index 2
np.insert(array,2,(78,709))

array([  2,   4,  78, 709,   6,   5,   3,   2,   4,   5,   4,   8,   9,
         7,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0])

In [274]:
#delete the index 3 row
np.delete(array,3,axis = 0)

array([[2, 4, 6, 5],
       [3, 2, 4, 5],
       [4, 8, 9, 7],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [275]:
#delete the index 2 column
np.delete(array,2,axis =1)

array([[2, 4, 5],
       [3, 2, 5],
       [4, 8, 7],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [280]:
#mean of total array
np.mean(array)
#mean of each column
np.mean(array,axis=0)
#mean of each row
np.mean(array,axis=1)

array([4.25, 3.5 , 7.  , 0.  , 0.  , 0.  ])

In [306]:
array.sum()
array.min(axis=0)
array.max()
#variance de l'array
np.var(array)
#standard deviation
np.std(array,axis =0)
np.corrcoef(array[0:3,0:3])
np.median(array)

1.0

In [328]:
#add 10 to each member of the array
np.add(array,10)
np.multiply(array,3)
np.subtract(array,2)
np.power(array,3)
np.divide(array,2)

#works with another array
np.add(array,array)

array([[ 4,  8, 12, 10],
       [ 6,  4,  8, 10],
       [ 8, 16, 18, 14],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0]])

In [335]:
np.sqrt(array)
np.log(array)
np.abs(array)
np.cos(array)
#return True if both arrays are equal
np.array_equal(tree,test)

C:\Users\vbigand\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


True

In [338]:
# round up to the nearest integer
np.ceil(array)
# round down to the nearest integer
np.floor(array)
# round to the nearest integer
np.round(array)

array([[2, 4, 6, 5],
       [3, 2, 4, 5],
       [4, 8, 9, 7],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])